import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import MobileNavbar from "@/components/Navbar/MobileNavbar";
import Footer from "@/components/Footer/Footer";
import ScrollToTop from "@/components/OtherComponents/ScrollToTop";

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <ScrollToTop />
        <Navbar />
        <MobileNavbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
